[functions.uk_aq_pcon_hex]
verify_jwt = false

[functions.uk_aq_la_hex]
verify_jwt = false

[functions.uk_aq_latest]
verify_jwt = false

[functions.uk_aq_stations_chart]
verify_jwt = false

[functions.uk_aq_stations]
verify_jwt = false

[functions.uk_aq_public_networks]
verify_jwt = false

[functions.uk_aq_timeseries]
verify_jwt = false

[functions.uk_aq_station_snapshot]
verify_jwt = false

[functions.uk_aq_egress_monitor]
verify_jwt = false

[functions.uk_aq_dispatch_polls]
verify_jwt = false

[functions.ingest_sos]
verify_jwt = false

[functions.ingest_breathelondon]
verify_jwt = false

[functions.ingest_sensorcommunity]
verify_jwt = false

[functions.ingest_openaq]
verify_jwt = false

[functions.ingest_erg_laqn]
verify_jwt = false
